export const TEST_ID = {
  CONTAINER: 'SIGN_IN_CONTAINER',
  PHONE_NUMBER_CONTROLLER: 'SIGN_IN_PHONE_NUMBER_CONTROLLER',
  PASSWORD_CONTROLLER: 'SIGN_IN_PASSWORD_CONTROLLER',
  CONFIRM_PASSWORD_CONTROLLER: 'SIGN_IN_CONFIRM_PASSWORD_CONTROLLER',
  CONFIRM_BUTTON: 'SIGN_IN_CONFIRM_BUTTON',
};
