name: Discord
on: pull_request
jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Discord Message Notify
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.WEBHOOK_TOKEN }}
          username: GitHub
          message: "A new pull request has been opened or updated at ${{ github.event.repository.name }}.
          \nPlease, Check it out at ${{ github.event.pull_request.html_url }}."
