name: Lint
on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Run ESLint
        run: yarn lint
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Run Typescript check
        run: yarn tsc
